In [ ]:
x <- matrix(nrow = 4, ncol = 3, data = 1:12)
x

rownames(x) <- c("r1", "r2", "r3", "r4")
colnames(x) <- c("c1", "c2", "c3")
x

     [,1] [,2] [,3]
[1,] 1    5     9
[2,] 2    6    10
[3,] 3    7    11
[4,] 4    8    12

   c1 c2 c3
r1 1  5   9
r2 2  6  10
r3 3  7  11
r4 4  8  12

In [ ]:
x <- matrix(nrow = 4, ncol = 2, data = 2)
x

d <- diag(1, nrow = 3, ncol = 3)
d

d <- diag(5, nrow = 3, ncol = 3)
d

     [,1] [,2]
[1,] 2    2
[2,] 2    2
[3,] 2    2
[4,] 2    2

     [,1] [,2] [,3]
[1,] 1    0    0
[2,] 0    1    0
[3,] 0    0    1

     [,1] [,2] [,3]
[1,] 5    0    0
[2,] 0    5    0
[3,] 0    0    5

In [ ]:
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = 1:8,
  byrow = TRUE
)

x
t(x)

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 1    3    5    7
[2,] 2    4    6    8

In [ ]:
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = 1:8
)

x

rowSums(x)
colSums(x)

rowMeans(x)
colMeans(x)

     [,1] [,2]
[1,] 1    5
[2,] 2    6
[3,] 3    7
[4,] 4    8

[1]  6  8 10 12

[1] 10 26

[1] 3 4 5 6

[1] 2.5 6.5

In [ ]:
# acessing rows,columns
x <- matrix(
  nrow = 5,
  ncol = 3,
  byrow = TRUE,
  data = 1:15
)

x

     [,1] [,2] [,3]
[1,]  1    2    3
[2,]  4    5    6
[3,]  7    8    9
[4,] 10   11   12
[5,] 13   14   15

In [ ]:
x[3, ]

[1] 7 8 9

In [ ]:
x[, 2]

[1]  2  5  8 11 14

In [ ]:
# Matrix with a constant , Addition and Subtraction
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = 1:8,
  byrow = TRUE
)

x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
x + 5
x-5

     [,1] [,2]
[1,]  6    7
[2,]  8    9
[3,] 10   11
[4,] 12   13

     [,1] [,2]
[1,] -4   -3
[2,] -2   -1
[3,]  0    1
[4,]  2    3

In [ ]:
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = 1:8,
  byrow = TRUE
)

x

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

In [ ]:
4 * x

     [,1] [,2]
[1,]  4    8
[2,] 12   16
[3,] 20   24
[4,] 28   32

In [ ]:
x + 4 * x

     [,1] [,2]
[1,]  5   10
[2,] 15   20
[3,] 25   30
[4,] 35   40

In [ ]:
x <- matrix(
  nrow = 4,
  ncol = 2,
  data = 1:8,
  byrow = TRUE
)

y <- matrix(
  nrow = 2,
  ncol = 4,
  data = 11:18,
  byrow = TRUE
)

x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6
[4,] 7    8

     [,1] [,2] [,3] [,4]
[1,] 11   12   13   14
[2,] 15   16   17   18

In [ ]:
x %*% y

     [,1] [,2] [,3] [,4]
[1,]  41   44   47   50
[2,]  93  100  107  114
[3,] 145  156  167  178
[4,] 197  212  227  242

In [ ]:
crossprod(x)

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
x <- matrix(
  nrow = 3,
  ncol = 2,
  data = 1:6,
  byrow = TRUE
)

y <- matrix(
  nrow = 3,
  ncol = 2,
  data = 11:16,
  byrow = TRUE
)

x
y

     [,1] [,2]
[1,] 1    2
[2,] 3    4
[3,] 5    6

     [,1] [,2]
[1,] 11   12
[2,] 13   14
[3,] 15   16

In [ ]:
rbind(x, y)

     [,1] [,2]
[1,]  1    2
[2,]  3    4
[3,]  5    6
[4,] 11   12
[5,] 13   14
[6,] 15   16

In [ ]:
cbind(x, y)

     [,1] [,2] [,3] [,4]
[1,] 1    2    11   12
[2,] 3    4    13   14
[3,] 5    6    15   16

In [ ]:
y <- matrix(
  nrow = 2,
  ncol = 2,
  byrow = TRUE,
  data = c(84, 100, 100, 120)
)

y

     [,1] [,2]
[1,]  84  100
[2,] 100  120

In [ ]:
solve(y)

     [,1]  [,2]
[1,]  1.50 -1.25
[2,] -1.25  1.05

In [ ]:
e <- eigen(y)

e

eigen() decomposition
$values
[1] 203.6070864   0.3929136

$vectors
          [,1]       [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230

In [ ]:
e$values

[1] 203.6070864   0.3929136

In [ ]:
e$vectors

     [,1]      [,2]
[1,] 0.6414230 -0.7671874
[2,] 0.7671874  0.6414230