In [47]:
# missing Data
x <- NA
is.na(x)

[1] TRUE

In [2]:
x_vec <- c(11, NA, 13, NA)
is.na(x_vec)

[1] FALSE  TRUE FALSE  TRUE

In [8]:
x <- c(11, NA, 13, NA)
mean(x)
mean(x, na.rm = TRUE)
x <- c(11, NA, 13, NA)
# loc of na
which(is.na(x))
# count of na
sum(is.na(x))

[1] NA

[1] 12

[1] 2 4

[1] 2

In [14]:
# Finding Complete Cases and Omitting NAs
x <- c(11, NA, 13, NA)
complete.cases(x)
y <- na.omit(x)
y

mean(y)

[1]  TRUE FALSE  TRUE FALSE

[1] 11 13
attr(,"na.action")
[1] 2 4
attr(,"class")
[1] "omit"

[1] 12

In [16]:
# if condN
x <- 5
if (x > 4) {
  x * 3
}

x <- 6
if (x > 3) {
  print("The value is more than 3")
}

[1] 15

[1] "The value is more than 3"

In [41]:
#if else
x <- 5
if (x == 3) {
  x <- x - 1
} else {
  x <- 2 * x
}
x


x <- 3
if (x == 3) {
  x <- x - 1
} else {
  x <- 2 * x
}
print(x)



x <- 6
if (x > 3) {
  print("The value is more than 3")
} else {
  print("The value is less than 3")
}

[1] 10

[1] 2
[1] "The value is more than 3"

In [44]:
# nested if else
x <- 5
if (x == 3) {
  x <- x - 1
} else if (x < 3) {
  x <- x + 5
} else {
  x <- 2 * x
}
x

x <- 3
if (x == 3) {
  x <- x - 1
} else if (x < 3) {
  x <- x + 5
} else {
  x <- 2 * x
}
x

[1] 10

[1] 2

In [23]:
# vectorized if else
x <- 1:10
ifelse(x < 6, x^2, x + 1)

 [1]  1  4  9 16 25  7  8  9 10 11

In [24]:
x <- c(7, 9, 8, 4)
ifelse(x %% 2 == 0, "even number", "odd number")

[1] "odd number"  "odd number"  "even number" "even number"

In [29]:
# return 2 ele
switch(2, "apple", "banana", "orange")

[1] "banana"

In [30]:

switch("colour", "colour" = "blue", "gender" = "male", "volume" = 50)

[1] "blue"

In [31]:
x <- c(10, 15, 8, 14, 6, 12)

which(x == 14)
which(x != 12)
which(x > 10)

[1] 4

[1] 1 2 3 4 5

[1] 2 4 6

In [38]:
x <- matrix(nrow = 3, ncol = 3, data = 1:9)
x

# min amd max values index
which.min(x)
which.max(x)


# odd numbers
which(x %% 2 == 1)

# array indices (row and col coordinates)
which(x %% 2 == 1, arr.ind = TRUE)

     [,1] [,2] [,3]
[1,] 1    4    7
[2,] 2    5    8
[3,] 3    6    9

[1] 1

[1] 9

[1] 1 3 5 7 9

     row col
[1,] 1   1
[2,] 3   1
[3,] 2   2
[4,] 1   3
[5,] 3   3